<template>
    <div id='category'>
    <h2>分类</h2>
    <scroll>
        <ul>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
            <li>列表1</li>
        </ul>
    </scroll>
    </div>


</template>

<script>
import scroll from 'components/common/BScroll/BScroll.vue'
export default {
    name:'category_index',
    components:{
        scroll,
    }
}
</script>